<?php
// Script para regenerar autoload
require_once 'vendor/autoload.php';

// Gerar classmap
$composer = json_decode(file_get_contents('composer.json'), true);

// Buscar por todas as classes PHP
$iterator = new RecursiveIteratorIterator(
    new RecursiveDirectoryIterator('app', RecursiveDirectoryIterator::SKIP_DOTS),
    RecursiveIteratorIterator::LEAVES_ONLY
);

$classmap = [];
foreach ($iterator as $file) {
    if ($file->getExtension() === 'php') {
        $content = file_get_contents($file->getPathname());
        if (preg_match('/namespace\s+([^;]+);/', $content, $namespaceMatch)) {
            if (preg_match('/class\s+([A-Za-z0-9_]+)/', $content, $classMatch)) {
                $fullClass = $namespaceMatch[1] . '\\' . $classMatch[1];
                $classmap[$fullClass] = $file->getPathname();
                echo "Found: $fullClass -> " . $file->getPathname() . "\n";
            }
        }
    }
}

// Salvar no arquivo de autoload
$autoloadFile = 'vendor/composer/autoload_classmap.php';
$currentAutoload = include $autoloadFile;

$newAutoload = array_merge($currentAutoload, $classmap);

$content = "<?php\n\n// autoload_classmap.php @generated by Composer\n\n";
$content .= "\$vendorDir = dirname(__DIR__);\n";
$content .= "\$baseDir = dirname(\$vendorDir);\n\n";
$content .= "return array(\n";

foreach ($newAutoload as $class => $path) {
    $relativePath = str_replace('\\', '/', $path);
    if (strpos($relativePath, 'app/') === 0) {
        $content .= "    '$class' => \$baseDir . '/$relativePath',\n";
    } else {
        $content .= "    '$class' => '$path',\n";
    }
}

$content .= ");\n";

file_put_contents($autoloadFile, $content);
echo "Autoload regenerated!\n";
